honorifics:
  - "고객님"
  - "님"
  - "께서"
  - "시"
  - "셔"
  - "십니다"
  - "십니까"
  - "세요"
positive:
  - "네"
  - "맞습니다"
  - "좋습니다"
  - "감사합니다"
  - "가능합니다"
  - "알겠습니다"
negative:
  - "안됩니다"
  - "어렵습니다"
  - "죄송합니다"
  - "불가능합니다"
euphonious:
  - "혹시"
  - "괜찮으시다면"
  - "~해주시겠어요"
  - "~일 수 있습니다"
apology:
  - "죄송합니다"
  - "사과드립니다"
  - "미안합니다"
empathy:
  - "그러셨군요"
  - "힘드셨겠어요"
  - "공감합니다"
  - "이해합니다"