empathy_roots:
  - "공감"
  - "이해"
  - "걱정"
  - "마음"
empathy_patterns:
  - "하셨겠어요"
  - "하셨겠네요"
  - "그러셨군요"
  - "힘드셨죠"
  - "저런"
  - "아이고"
apology_roots:
  - "죄송"
  - "사과"
  - "미안"
  - "양해"
cushion:
  - "실례지만"
  - "죄송하지만"
  - "괜찮으시다면"
  - "혹시"
  - "번거로우시겠지만"
  - "만약"
  - "양해 부탁드립니다"
  - "잠시만"